#mybatis配置xml文件
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml



spring:

#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.101.58.140:3306/sharding_db?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: 111111


  shardingsphere:
    datasource:
      names: m1
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.101.58.140:3306/sharding_db?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 111111
    sharding:
      tables:
        course:
          #配置 course 表规则
          actual-data-nodes: m1.course_$->{1..2}
          #表分片策略
          table-strategy:
            inline:
              sharding-column: cid
              algorithm-expression: course_$->{cid%2 + 1}
          # 指定 course 表里边主键生成策略   SNOWFLAKE   雪花算法
          key-generator:
            column: cid
            type: SNOWFLAKE



    props:
      sql:
        show: true
  main:
    allow-bean-definition-overriding: true